---
layout: page
title: Github JS Widgets
minify_content: false
navigation:
  - name: Home
    link: /
    icon: fa fa-home

  - name: Overview
    link: /github-jquery-widgets
    icon: fa fa-dashboard

  - name: Demonstration
    link: /github-jquery-widgets/demo
    icon: fa fa-record

  - name: Coverage
    link: /github-jquery-widgets/coverage
    icon: fa fa-code

---
